/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_aki_demo_jni_JniUtils */

#ifndef _Included_cn_aki_demo_jni_JniUtils
#define _Included_cn_aki_demo_jni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_aki_demo_jni_JniUtils
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_aki_demo_jni_JniUtils_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
